### ISSUE TITLE
Crashes on startup: cannot import 'allowed_parsers'

### ISSUE THREAD

**Issue by jeffteeters** [G-Node/odml-ui#119] opened 2018-04-10 18:20 UTC
This is with a fresh install of both `python_odml` and `odml_ui` in a new conda environment (Python 3.6).  Gives the following error on startup.  It appears that, `python_odml` file `odml/tools/odmlparser.py` was modified to remove 'allowed_parsers' but the code in `odml_ui` is still expecting it.

```
(pyodML) odml-ui jt$ python odml-gui
2018-04-10 10:56:05.873 python[66960:9743992] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
Traceback (most recent call last):
  File "odml-gui", line 2, in <module>
    from odmlui import __main__
  File "/Users/jt/toolbox/odml-ui/odmlui/__main__.py", line 10, in <module>
    from . import Editor
  File "/Users/jt/toolbox/odml-ui/odmlui/Editor.py", line 25, in <module>
    from .EditorTab import EditorTab
  File "/Users/jt/toolbox/odml-ui/odmlui/EditorTab.py", line 15, in <module>
    from .Helpers import uri_to_path, get_parser_for_uri, get_extension, \
  File "/Users/jt/toolbox/odml-ui/odmlui/Helpers.py", line 7, in <module>
    from odml.tools.odmlparser import allowed_parsers
ImportError: cannot import name 'allowed_parsers'
```

**Comment by jgrewe** [comment] 2018-04-10 19:44
Hi @jeffteeters, how did you install the core odml library? Was it automatically pulled in by conda?  In case you installed from source, the current version is in the 1.3 branch for both the odml-ui and python-odml. The master, respectively the development branches will not work.

**Comment by jeffteeters** [comment] 2018-04-10 19:52
I installed by source, the development branch.  I'll try the 1.3 branch.  Thanks.

**Comment by jeffteeters** [comment] 2018-04-10 21:29
I switched to the 1.3 branch for both repositories and removed all the previously installed odML egg directories and reinstalled.  Now I get a different error on startup.  The versions I'm running in the environment are:

```
$ ls -d /Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/odML*
/Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/odML-1.3.3-py3.6.egg
/Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/odML_UI-1.3.0-py3.6.egg

```
The error I get is:

```
(pyodML) jt$ python odml-gui
2018-04-10 14:19:20.663 python[68971:9836957] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
[Info] Updating IconTheme search path
Attribute error when trying to call set_screen, parent=None
screen is <__gi__.GdkQuartzScreen object at 0x10dcde900 (GdkQuartzScreen at 0x7f9afd0e00c0)>, screen_a_window=None
Traceback (most recent call last):
  File "odml-gui", line 5, in <module>
    __main__.run()
  File "/Users/jt/toolbox/odml-ui/odmlui/__main__.py", line 52, in run
    main(filenames=args.files, debug=args.debug)
  File "/Users/jt/toolbox/odml-ui/odmlui/__main__.py", line 23, in main
    editor = Editor.EditorWindow()
  File "/Users/jt/toolbox/odml-ui/odmlui/Editor.py", line 192, in __init__
    currmon = screen.get_monitor_at_window(screen.get_active_window())
TypeError: Argument 1 does not allow None as a value
```
This is on a mac, OS-X 10.13.3, Python 3.6.  The error occurred when trying to run in a normal terminal shell and also in a x-windows shell (using XQuartz).  By inserting the print statement shown below in file `odmlui/Editor.py` I determined that the call to `screen.get_active_window()` is returning `None` (see output of print statements above).  Perhaps that will help figure out what is causing the problem.

```
class EditorWindow(gtk.Window):
    odMLHomepage = HOMEPAGE
    registry = DocumentRegistry()
    editors = set()
    welcome_disabled_actions = ["Save", "SaveAs", "NewSection", "NewProperty",
                                "NewValue", "Delete", "CloneTab", "Map", "Validate",
				"odMLTablesCompare", "odMLTablesConvert",
                                "odMLTablesFilter", "odMLTablesMerge"]

    def __init__(self, parent=None):
        gtk.Window.__init__(self)
        self.editors.add(self)
        try:
            self.set_screen(parent.get_screen())
	except AttributeError:
            print ("Attribute error when trying to call set_screen, parent=%s" % parent)
            self.connect('delete-event', self.close)

        self.set_title("odML Editor")
        self.set_default_size(800, 600)

        # Check available screen size and adjust default app size to 1024x768 if possible.                                                            
        screen = self.get_screen()
        screen_a_window = screen.get_active_window()
        print("screen is %s, screen_a_window=%s" % (screen, screen_a_window))
        currmon = screen.get_monitor_at_window(screen.get_active_window())
```

 Any suggestions for how to fix this?

**Comment by mpsonntag** [comment] 2018-04-11 08:30
Hi @jeffteeters, I have a fix for this, but it has not been merge yet into the current 1.3 master branch. On short notice you can find a hotfix [here](https://github.com/mpsonntag/odml-ui/commit/ee79460023601eaffe7d026a542c0240cefcde0b) but it should be in the 1.3 master branch until next week.

**Comment by jeffteeters** [comment] 2018-04-11 21:37
The hotfix worked (allowed the application to start).  Thanks for providing it!

It appears that most of the application is working for me (I'm able to create a new document and edit it).  However, the program crashes when I try to either save or open a file.  Also, there is a warning and several Info messages displayed on startup, one of the info messages seems like it could be reporting a problem "No module named 'odmltables'."  The terminal output is shown below from startup to crash for both attempting to open a file and editing a document and attempting to save a file.
```
(pyodML) odml-ui jt$ # try opening file
(pyodML) odml-ui jt$ python odml-gui
2018-04-11 13:45:18.078 python[75042:10185446] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
[Info] Updating IconTheme search path
[Info] odMLTables not available: No module named 'odmltables'
# program crashes when following message is displayed (when clicking on icon to open a file)
(odml-gui:75042): GLib-GIO-ERROR **: 13:45:32.630: No GSettings schemas are installed on the system
Trace/BPT trap: 5

(pyodML) odml-ui jt$ # try saving a file
(pyodML) odml-ui jt$ python odml-gui
2018-04-11 13:45:49.658 python[75054:10186107] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
[Info] Updating IconTheme search path
[Info] odMLTables not available: No module named 'odmltables'

# Following messages displayed when deleting unused properties from the odML section
warning[http://portal.g-node.org/odml/terminologies/v1.0/questionnaire/questionnaire.xml:33:<value>]: cannot set 'dtype' property on <value>: AttributeError("'question' is not a valid type.",)
warning[http://portal.g-node.org/odml/terminologies/v1.0/questionnaire/questionnaire.xml:42:<value>]: cannot set 'dtype' property on <value>: AttributeError("'File' is not a valid type.",)
Traceback (most recent call last):
  File "/Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/pygtkcompat/generictreemodel.py", line 60, in wrapped_func
    return func(*args, **kargs)
  File "/Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/pygtkcompat/generictreemodel.py", line 252, in do_get_path
    return Gtk.TreePath(path)
  File "/Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 1186, in __new__
    raise TypeError("could not parse subscript '%s' as a tree path" % path)
TypeError: could not parse subscript '' as a tree path
Traceback (most recent call last):
  File "/Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/pygtkcompat/generictreemodel.py", line 60, in wrapped_func
    return func(*args, **kargs)
  File "/Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/pygtkcompat/generictreemodel.py", line 252, in do_get_path
    return Gtk.TreePath(path)
  File "/Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 1186, in __new__
    raise TypeError("could not parse subscript '%s' as a tree path" % path)
TypeError: could not parse subscript '' as a tree path
Traceback (most recent call last):
  File "/Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/pygtkcompat/generictreemodel.py", line 60, in wrapped_func
    return func(*args, **kargs)
  File "/Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/pygtkcompat/generictreemodel.py", line 252, in do_get_path
    return Gtk.TreePath(path)
  File "/Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 1186, in __new__
    raise TypeError("could not parse subscript '%s' as a tree path" % path)
TypeError: could not parse subscript '' as a tree path
Traceback (most recent call last):
  File "/Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/pygtkcompat/generictreemodel.py", line 60, in wrapped_func
    return func(*args, **kargs)
  File "/Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/pygtkcompat/generictreemodel.py", line 252, in do_get_path
    return Gtk.TreePath(path)
  File "/Users/jt/anaconda/envs/pyodML/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 1186, in __new__
    raise TypeError("could not parse subscript '%s' as a tree path" % path)
TypeError: could not parse subscript '' as a tree path

# Following is displayed when clicking on icon to save the file (program crashes)
(odml-gui:75054): GLib-GIO-ERROR **: 13:46:45.308: No GSettings schemas are installed on the system
Trace/BPT trap: 5
(pyodML) odml-ui jt$ 
```

I tried to figure out what is causing the error: `GLib-GIO-ERROR **: No GSettings schemas are installed on the system`

I didn't find anything useful specific to a mac.  Found this related to windows:

[https://stackoverflow.com/questions/24370294/glib-gio-error-when-opening-an-file-chooser-dialog](https://stackoverflow.com/questions/24370294/glib-gio-error-when-opening-an-file-chooser-dialog)

It suggests setting an environment variable to point to the directory of the schemas.  I think I was able to find the location of the schemas, and I tried setting the environment variable, (shown below), but that didn't help.

```
(pyodML) jt$ ls -l /Users/jt/anaconda/envs/pyodML/share/glib-2.0/schemas
total 64
-rw-rw-r--  2 jt  staff  2839 Nov 24 14:44 gschema.dtd
-rw-rw-r--  3 jt  staff  2438 Oct  7  2016 gschemas.compiled
-rw-rw-r--  3 jt  staff   375 Oct  7  2016 org.gtk.Demo.gschema.xml
-rw-rw-r--  3 jt  staff   931 Oct  7  2016 org.gtk.Settings.ColorChooser.gschema.xml
-rw-rw-r--  3 jt  staff   832 Oct  7  2016 org.gtk.Settings.Debug.gschema.xml
-rw-rw-r--  3 jt  staff  4950 Oct  7  2016 org.gtk.Settings.FileChooser.gschema.xml
-rw-rw-r--  3 jt  staff   845 Oct  7  2016 org.gtk.exampleapp.gschema.xml
(pyodML) jt$ export XDG_DATA_DIRS=/Users/jt/anaconda/envs/pyodML/share/glib-2.0/schemas
```

btw, I noticed that file `odml-ui/resources/install_conda.sh` has a code block executed for linux systems which is the same as what what I did to install the dependencies using conda; it has a comment saying:

`# Currently there is still a dependency mixup for conda under osx.`

Perhaps this comment is referring to something related to the GLib-GIO-ERROR I'm getting.

Have any suggestions for the next step?

**Comment by mpsonntag** [comment] 2018-04-16 09:24
I debugged this issue for both loading and saving and found, that both crash with the current Mac OS-X conda dependencies when initializing the GTK `Dialog` class. Since it is a proper crash (`Trace/BPT trap: 5`) I was not able to debug any further than that.
I played around with the currently available various conda dependencies for Mac since odml-ui currently works fine under Linux, but was so far not able to find a combination of dependencies that does not elicit this dependency crash for Mac OS-X with conda.

**Comment by mpsonntag** [comment] 2018-04-16 09:26
Maybe there are other GTK3 dependencies we can use for Mac OS-X conda or maybe there is a different GTK baseclass we can use for our custom `ChooserDialog`, but that seems to be just a circumvention of a base dependency issue.

**Comment by mpsonntag** [comment] 2018-04-16 13:50
I tested installing the GTK, pygobject, gobject-introspection and icon-theme dependencies on MacOS via homebrew (see README.rst) and used a python virtual environment with the `--system-site-packages` flag where I installed `python-odml` and `odml-ui` via pip from source which then worked fine for loading and saving of files.

I guess for now this is our recommended install of odml-ui for Mac OS-X until we can provide a proper odml-ui app for Mac which bundles all dependencies.

**Comment by jeffteeters** [comment] 2018-04-17 01:59
Thanks for figuring this out.  I was able to get it working using the steps you described.  A few issues came up when setting up the python virtualenv and also using pip to install odml.   In case it's useful for others, the issues and steps I took to fix them are described below.  Also, at the bottom are shown some error messages I got when running the application in case that is useful.

After installing homebrew using:

```
~ jt$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
I then installed the dependencies using:
```
brew install gtk+3
brew install pygobject3
brew install gnome-icon-theme
brew install gobject-introspection
Warning: gobject-introspection 1.56.1 is already installed and up-to-date
```
(gobject-introspection didn't need to be installed explicitly because it was automatically installed previously).

I then installed virtualenv, and updated it:

```
jt$ /usr/local/bin/pip3 install virtualenv
Successfully installed virtualenv-15.2.0
You are using pip version 9.0.3, however version 10.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
jt$ /usr/local/bin/pip3 install --upgrade pip setuptools wheel
```

I then created the virtual environment (I name it "odmlve", inside directory "toolbox2") using:

```
/usr/local/bin/virtualenv ~/toolbox2/odmlve --system-site-packages
```
When inside the created ~/toolbox2/odmlve/bin directory, I had to specify a path when using "source activate", e.g. include "./" in "source ./activate" otherwise the environment was displayed as (root) instead of (odmlve).  The command to deactivate the environment didn't work.  e.g. the environment was still active after entering it:

```
(odmlve) bin jt$ source deactivate
(odmlve) bin jt$ 
```
I found in StackOverflow that the conda deactivate conflicts with the python virtualenv deactivate. 
[https://stackoverflow.com/questions/30308190/deactivate-conflict-in-virtualenvwapper-and-anaconda](https://stackoverflow.com/questions/30308190/deactivate-conflict-in-virtualenvwapper-and-anaconda)

To fix this I copied the bin/activate script to "bin/activate_odml" and renamed function "deactivate" to "deactivate_odml".  That worked, allowing:
```
bin jt$ source ./activate_odml 
(odmlve) bin jt$ deactivate_odml
bin jt$ source ./activate_odml 

```

Once the virtualenv was setup, I then tried to install odml via pip (pip3 for Python 3).  When doing this, the lxml and yaml dependencies were not automatically installed, causing error messages to be displayed when trying to install odml.  I had to install them manually using:

```
pip3 install lxml
pip3 install PyYAML
```
Then 
`pip3 install odml`
worked.


After getting odml installed, I was then able to install odml-ui from source using:
```
odml-ui jt$ python setup.py install
 ```

It did crash once when I was editing some properties in an odML file, but so far, I have not been able to reproduce the crash.

I did get some error messages on startup and when opening a file:

```
(odmlve)  jt$ python odml-gui
[Info] Updating IconTheme search path
[Info] odMLTables not available: No module named 'odmltables'
warning[http://portal.g-node.org/odml/terminologies/v1.0/questionnaire/questionnaire.xml:33:<value>]: cannot set 'dtype' property on <value>: AttributeError("'question' is not a valid type.",)
warning[http://portal.g-node.org/odml/terminologies/v1.0/questionnaire/questionnaire.xml:42:<value>]: cannot set 'dtype' property on <value>: AttributeError("'File' is not a valid type.",)
```

And when running the application, there was a large stream of error messages displayed.  They appeared to be the error below repeated many times.  I'm not sure what I was doing when the messages were displayed.
```
Traceback (most recent call last):
  File "/Users/jt/toolbox/odml-ui/odmlui/PropertyView.py", line 95, in dtype_renderer_function
    cell_data = tree_model.get(tree_iter, data)[0]
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 907, in get
    values.append(self.get_value(treeiter, col))
TypeError: unknown type (null)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygtkcompat/generictreemodel.py", line 60, in wrapped_func
    return func(*args, **kargs)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pygtkcompat/generictreemodel.py", line 257, in do_get_value
    return self.on_get_value(self.get_user_data(iter), column)
  File "/Users/jt/toolbox/odml-ui/odmlui/treemodel/PropertyModel.py", line 63, in on_get_value
    v = super(PropertyModel, self).on_get_value(tree_iter, column)
  File "/Users/jt/toolbox/odml-ui/odmlui/treemodel/TreeModel.py", line 111, in on_get_value
    debug(":on_get_value [%d:%s]: %s" % (column, attr, tree_iter))
  File "/Users/jt/toolbox/odml-ui/odmlui/treemodel/GenericIter.py", line 86, in __repr__
    repr(self._obj),
  File "/Users/jt/toolbox2/odmlve/lib/python3.6/site-packages/odml/value.py", line 90, in __repr__
    return "<%s %s>" % (str(self._dtype), self.get_display())
  File "/Users/jt/toolbox2/odmlve/lib/python3.6/site-packages/odml/value.py", line 297, in get_display
    if self.can_display(text, max_length):
  File "/Users/jt/toolbox2/odmlve/lib/python3.6/site-packages/odml/value.py", line 282, in can_display
    if self._encoder is None and len(unprintable) > 0:
TypeError: object of type 'filter' has no len()
```

**Comment by mpsonntag** [comment] 2018-04-17 18:49
Thanks for the detailed installation description!

**Comment by mpsonntag** [comment] 2018-04-17 18:51
Regarding the errors: the installation error should be resolved once the currently open PR was merged. Regarding the runtime error: we will investigate this and move them to their individual issues once we have reproduced them, thanks again for reporting!

**Comment by mpsonntag** [comment] 2018-06-07 14:45
I found a fix for using conda with MacOS:

The MacOS installation of the 3rd party gtk3 dependencies contain a bug which causes
the opening of any window selecting files to crash the application.

To use odmlui with conda on MacOS, a manual fix at the start of a session needs to be applied in the active conda environment to avert this crash:

`export GSETTINGS_SCHEMA_DIR=$CONDA_PREFIX/share/glib-2.0/schemas`

Scripts can be added to the conda environment to automatically set up the
required environment variable at the start of a conda session as described in the [conda documentation](https://conda.io/docs/user-guide/tasks/manage-environments.html#macos-linux-save-env-variables).

**Closed as completed** 2018-06-11 07:53 UTC
